### ISSUE TITLE
The specified module could not be found (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#12]
KABOOOOOM ERROR WITH WINDOWS XP SP3 (Net framework 4.0 and xna both updated)
![karucw](https://cloud.githubusercontent.com/assets/6104940/20865051/d9d9c98c-b9fe-11e6-9974-5fd2580ca9c7.jpg)

Log file - https://forums.cncnet.org/index.php?topic=6909.0;topicseen

**Comment by heckfreeze** [comment]
![pro](https://cloud.githubusercontent.com/assets/24368095/20865458/6bd9d0fe-ba34-11e6-87b5-d892e9b98e1a.jpg)
do i need to update DirectX?

**Comment by GrantBartlett** [comment]
Quite possibly, I think you need Directx11

**Comment by heckfreeze** [comment]
hey grant , i saw a post that directx11 is for vista only not for xp , if not then can  you suggest me download link for win xp sp3

**Comment by heckfreeze** [comment]
https://snag.gy/mOuAUz.jpg

**Comment by Rampastring** [comment]
Hm, for some reason the shortcut (CnCNetYRLauncher.exe) is detecting your OS wrong. Try running Resources\clientxna.exe directly and see if that works.

**Comment by heckfreeze** [comment]
Same Error for clientxna.exe

**Comment by Rampastring** [comment]
Grant, on XP the client only needs XNA and DirectX 9.0c. DX11 is only needed on Vista and newer.

@heckfreeze: Have you uninstalled Internet Explorer in some way?

**Comment by heckfreeze** [comment]
nope i didn't uninstalled IE why do i need to anyway ?

**Comment by heckfreeze** [comment]
Are you guys going to update cncnet again in few days time ?

**Comment by GrantBartlett** [comment]
@heckfreeze could you try 3.0.36 update

**Comment by heckfreeze** [comment]
I cant update it, same error as before that kaboom error.

**Comment by GrantBartlett** [comment]
@heckfreeze try downloading this: https://downloads.cncnet.org/CnCNet5_YR_Installer.exe
running it into that directory, and seeing if it will update to the latest that way.

**Comment by heckfreeze** [comment]
alright let me try

**Comment by heckfreeze** [comment]
@GrantBartlett  hi , it did worked in sp3 thanks mate, but unfortunately my primary OS is win xp sp2 , and it is not working in that windows , i

**Comment by GrantBartlett** [comment]
@heckfreeze I believe you will need SP3 as a minimum.  @Rampastring this is correct?

**Comment by heckfreeze** [comment]
@GrantBartlett  https://snag.gy/cDUGgm.jpg

**Comment by heckfreeze** [comment]
@GrantBartlett  :/ thats a bad news then i dont think so sp3 is must, i previously was playing on cnc with sp2 3-4 days ago

**Comment by heckfreeze** [comment]
Its jerking way too much in sp3 and its getting disconnected after 10-20 seconds i connected .

**Comment by GrantBartlett** [comment]
If talking about when playing a game? 
@heckfreeze - make sure to look at the Renderer, TS-DDRAW works well. 
![options](https://cloud.githubusercontent.com/assets/6104940/20867476/2f7dc6c0-ba3d-11e6-8e92-1e5f9da53464.png)

**Comment by heckfreeze** [comment]
renderer was set to default, and when i manually selected ts-ddraw and closed client and re open then it gave kabooom error :/ @GrantBartlett

**Comment by heckfreeze** [comment]
My lobby is hang when  i logged in, https://snag.gy/T6lpk3.jpg

**Comment by heckfreeze** [comment]
i cant select yuri revenge here, https://snag.gy/S6dUE4.jpg

**Comment by heckfreeze** [comment]
i cant see game rooms at all, and cnc gets dc always after 30 sec whenever i login,

**Comment by Rampastring** [comment]
Yuri's Revenge is forced to be enabled there, the texture isn't very clear but it means that it's checked.

The new client indeed requires Service Pack 3 on Windows XP.

Upload your Client\client.log file to pastebin.com and link it here when you've got disconnected.

**Comment by heckfreeze** [comment]
well i tried all renderer not a single one worked fine cnc always dc or hang.  
here is client log link : http://www.filedropper.com/client_14

**Comment by Rampastring** [comment]
Hard to say why that happens, there's nothing visibly wrong in the log.

**Comment by heckfreeze** [comment]
maybe one of you have a teamviewer session with me ?

**Comment by heckfreeze** [comment]
[ClientCrashLog_4_12_2016_21_33.txt](https://github.com/CnCNet/xna-cncnet-client/files/632447/ClientCrashLog_4_12_2016_21_33.txt)
[ClientCrashLog_4_12_2016_21_49.txt](https://github.com/CnCNet/xna-cncnet-client/files/632448/ClientCrashLog_4_12_2016_21_49.txt)
[ClientCrashLog_5_12_2016_18_30.txt](https://github.com/CnCNet/xna-cncnet-client/files/632450/ClientCrashLog_5_12_2016_18_30.txt)
[ClientCrashLog_4_12_2016_21_9.txt](https://github.com/CnCNet/xna-cncnet-client/files/632449/ClientCrashLog_4_12_2016_21_9.txt)

Hi i found these files in errorlogs can you guys check what is wrong,

**Comment by heckfreeze** [comment]
?

**Comment by heckfreeze** [comment]
????? @GrantBartlett

**Comment by GrantBartlett** [comment]
`04.12. 21:49:40.546    Executing callback ⁯⁭‎⁯⁮⁯⁬‏‏‍⁯​‎⁮⁯‏⁯‍⁮⁭⁭​⁬⁯‏​‭⁬‍⁯‫⁫‌‪‍‌⁯⁮‫‏‮
04.12. 21:49:40.781    KABOOOOOOM!!! Info:
04.12. 21:49:40.781    Message: The parameter is incorrect
04.12. 21:49:40.921    Source: System
04.12. 21:49:40.921    TargetSite.Name: StartWithShellExecuteEx
04.12. 21:49:40.953    Stacktrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ‎‫‏‍‎‏⁫‮‭⁯⁫⁪⁪‮‬⁬‌‫‎⁮​⁭‏‪‪‭‪⁬‎‍⁫⁫‬‫‭⁫⁯⁪‫‌‮.​‫‌‭⁮‎‌⁮⁪‌‪‏⁮⁭‫‍⁭⁬⁮‬⁮‭‮⁬​⁬‫⁪‮⁯‌‭‍⁭‍⁫‪⁮⁬‏‮()
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAButton.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   at ClientGUI.DarkeningPanel.Update(GameTime gameTime)
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at ‭‏‮⁮⁯⁫‭‎⁬‮‍⁮​⁫‏‏‎⁬‌‮⁯‫‮​⁬⁯‮‪⁮⁬‬​⁫‪⁫‎‮⁪⁭‏‮.⁪⁬‫⁬‌⁬​⁮⁯‭⁮‮⁫‏‮​​‏⁬⁮‏⁭​​‍​⁮​‍‏⁫⁯⁯⁭⁫⁪⁯‍⁯⁬‮()
   at ​⁬⁫‭‭‍⁪‪⁬‪⁮⁬‬⁯⁪⁮⁪⁬⁮​‮​⁬‭‬⁫⁬⁪‌⁬‬‎‮⁪⁪⁮‭‬‪‬‮.⁯‎⁫⁯‍‌‮‮⁬​⁮⁫‮‌‬‮‪⁬⁪⁮⁪‏‌‌‎‏‪‌‮⁫‮‮‬​⁪⁬​⁫‏‪‮(String[] )
   at ​‪​‮⁬⁫‭‏⁯⁮‬⁪‮⁯⁬⁭‬‪​‎‫‮‍⁫⁪‌‏⁯‫‎⁯‬​‌‎​‏‎⁯⁬‮.‪⁭⁪‮‮‫⁪‪​⁮‭⁭‫⁮⁭​‭⁭⁬‫​‍‪‌⁭⁪‫‏⁪⁪​⁫⁭‏‭‏⁫⁯‏⁬‮(String[] )
`

Not sure what this is indicating at @Rampastring ?

**Comment by GrantBartlett** [comment]
@heckfreeze Tried the latest update, there's been a fair few improvements since. The above crashlogs we'll have to look into at some point.

**Comment by Rampastring** [comment]
Looks like in that case it crashed when trying to start something, most likely the main game executable. @heckfreeze, what were you doing at the time that crash occured?

**Comment by heckfreeze** [comment]
@Rampastring i was trying to create my game , but i cant see anyone else's game ,

**Comment by heckfreeze** [comment]
https://snag.gy/7pCXxw.jpg 
Modified files detected .

**Comment by GrantBartlett** [comment]
Update to the latest...

**Comment by heckfreeze** [comment]
i did, after that still i cant see map

**Comment by heckfreeze** [comment]
after updating , modified files error is not there though but i still cant see map

**Comment by GrantBartlett** [comment]
Client.log file, also rendering takes roughly 15 minutes currently as there
are a lot of maps, and it wasn't meant to render so many.

**Comment by heckfreeze** [comment]
@GrantBartlett  @Rampastring  my graphics were not good when i tried to play a game , it was not even loading properly , somehow when i managed to start the game my nick was haider and in game it was showing halder a very choppy graphics, so i decided to reinstall yuri and cncnet, when i did that i received new error :3
https://snag.gy/o5utAz.jpg

**Comment by heckfreeze** [comment]
I installed cncnet from this link  https://downloads.cncnet.org/CnCNet5_YR_Installer.exe 
and received a error,

**Comment by GrantBartlett** [comment]
You need .NET 4 framework

**Comment by heckfreeze** [comment]
grant i already have it, and its same windows, 15 mins ago i joined cnc lobby succesfully,

**Comment by GrantBartlett** [comment]
Log file ;)

**Comment by heckfreeze** [comment]
its not uploading here, wait a bit

**Comment by heckfreeze** [comment]
@GrantBartlett http://www.filedropper.com/client_16
client log

**Comment by GrantBartlett** [comment]
Wrong log, its in the Client folder. E.g - C:\Your PC\Game Directory\Client\client.log

**Comment by Rampastring** [comment]
That looks like the exact same error that you got first in this topic (the one related to IE / stats, which was fixed). Grant, is the installer up to date?

**Comment by GrantBartlett** [comment]
@heckfreeze - try http://grant.cnc-comm.com/tmp/CnCNet5_YR_Installer.exe

**Comment by heckfreeze** [comment]
somehow my cncnet worked but i still cant see maps,  already shared snapshot above

**Comment by heckfreeze** [comment]
@GrantBartlett  @Rampastring  http://www.filedropper.com/client_19 
log file

**Comment by Rampastring** [comment]
This is a YR-specific issue with map rendering.

**Comment by heckfreeze** [comment]
so whats the solution then

**Comment by Rampastring** [comment]
@heckfreeze I don't know, I haven't written the code that causes your problem. Ask @GrantBartlett

**Comment by heckfreeze** [comment]
@GrantBartlett  ?

**Comment by GrantBartlett** [comment]
Hello @heckfreeze - I'm unable to work on this until I get some free time this week. Rest assured I will look into it for you.  Thanks for being patient

**Comment by GrantBartlett** [comment]
@heckfreeze can you update to 3.0.46, join the lobby, exit, and upload client.log again. It will contain more debug info on the map problem hopefully.

**Comment by GrantBartlett** [comment]
@heckfreeze - someone else has this exact problem and it seems to be resolved, can you update and let us know if this now works for you?

**Comment by heckfreeze** [comment]
@GrantBartlett  hi i still cant see normal maps preview though i joined a room where host made a unofficial map i was able to see preview of that unofficial map, but i cant see official maps preview still

**Comment by heckfreeze** [comment]
@GrantBartlett  never mind , it worked for me either thanks mate , i can see maps now , though i want cnc net at sp2 :(

**Comment by heckfreeze** [comment]
grant my friend is banned from cnc net , his last nick was school and he said he was spamming in lobby thats why autobot banned him can u look into this thanks

**Comment by GrantBartlett** [comment]
SP2 does not meet the requirements for this new client anymore. You will have to update it. 
Regarding your friend, he should post in the forums for support.

Your issue seems resolved now so closing this. Thanks!

**Comment by heckfreeze** [comment]
https://forums.cncnet.org/index.php?topic=7050.0
