### ISSUE TITLE
The save/load settings function doesn't actually work

### ISSUE THREAD

**Issue by CCCP84** [CnCNet/xna-cncnet-client#795]
### Description

After loading the saved settings, if a player enters the room, the settings return to the original ones. The same thing happens if you change the map.
If you change the settings manually, this doesn't happen

<img width="778" height="527" alt="Image" src="https://github.com/user-attachments/assets/d54d961a-d4a2-45c2-83d7-0c9b94476fdb" />

Also, the save/load buttons have disappeared from the teams selection menu. This drop-down menu is now useless. But when it worked, the settings would also reset when the player entered the room.

<img width="773" height="458" alt="Image" src="https://github.com/user-attachments/assets/3f846e4d-c839-409e-85f0-8073f6b5626f" />

 I suggest that during fixing process we also get rid of the save/load drop-down menu in the additional settings menu, and make it so that additional settings (teams settings) are also saved through the load/save menu on the main screen.

I will also remind you about this [#796](https://github.com/CnCNet/xna-cncnet-client/issues/796) because it concerns the same complex.

And one more small point... I think superweapons should be disabled by default. Right now they are enabled by default.

<img width="528" height="391" alt="Image" src="https://github.com/user-attachments/assets/b333c622-e200-4362-a753-22ed742720ba" />

### XNA Client Version

yr-8.74.4

### Steps To Reproduce

1. Make changes
2. Save presets
3. Load presets
4. Other player enters room

### Expected Behaviour

Presets don't change

### Actual Behaviour

Presets reset to defaults

### Checklist

- [x] The issue happens on the **latest official** version of XNA Client and wasn't fixed yet.
- [x] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [x] I have attached as much information as possible *(screenshots, gifs, videos, client logs, etc)*.

**Comment by CCCP84** [comment]
This issue needs to be reopened because the downloaded settings change unpredictably when new players enter the room

**Comment by 11EJDE11** [comment]
That should be fixed with #878. It's not in live YR yet.

**Comment by CCCP84** [comment]
I'm writing this for a reason. I tried to use this function. It works poorly and constantly resets.
the problem is not solved

**Comment by 11EJDE11** [comment]
Have you tested the client with #878?

**Comment by CCCP84** [comment]
> Have you tested the client with [#878](https://github.com/CnCNet/xna-cncnet-client/pull/878)?

If it was updated just yesterday, then no. I'll try.
Or is this fix not yet added to Live?

**Comment by 11EJDE11** [comment]
I don't believe it's live in YR.

**Comment by CCCP84** [comment]
Then we need to do it faster. Why not update more often?

**Comment by CCCP84** [comment]
In general, we need to close the issue when it's solved in Live

**Comment by SadPencil** [comment]
> In general, we need to close the issue when it's solved in Live

This is the `xna-cncnet-client` repo. The issue is closed as long as it is merged into develop branch. You can only require an issue marked as solved in YR Live if the issue is in `cncnet-yr-client-package` repo
